### ISSUE TITLE
Does DAC support batch processing

### ISSUE THREAD

**Issue by feng-yufei** [descriptinc/descript-audio-codec#24]
Hi DAC team, 

I wonder whether it is possible to include an example in this repo that uses DAC to process audio in batches?

Thanks

**Comment by pseeth** [comment]
Hello! I have a PR in the works for this now. Will merge it soon! Thanks for checking our work out!

**Comment by pseeth** [comment]
This is now merged in the most recent DAC 1.0.0. Let me know if you have any issues! Use the `model.compress` and `model.decompress` functions.
