### ISSUE TITLE
entropy computation script not working (it used to work before)

### ISSUE THREAD

**Issue by listener17** [descriptinc/descript-audio-codec#30]
I downloaded the model weights from here: 
https://github.com/descriptinc/descript-audio-codec/releases/download/0.0.1/weights.pth

But the script: 
https://github.com/descriptinc/descript-audio-codec/blob/main/scripts/compute_entropy.py
does not work. 

**It used to work before the commit #22 last week.** 

Here is the error: 
```
descript-audio-codec$ CUDA_VISIBLE_DEVICES=3 python3 scripts/compute_entropy.py input/ weights.pth
  0%|                                                                                      | 0/3 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "/mnt/project/user/descript-audio-codec/scripts/compute_entropy.py", line 50, in <module>
    main()
  File "/home/user/miniconda3/envs/e2e/lib/python3.9/site-packages/argbind/argbind.py", line 159, in cmd_func
    return func(*cmd_args, **kwargs)
  File "/mnt/project/user/descript-audio-codec/scripts/compute_entropy.py", line 31, in main
    codes.append(o["codes"].cpu())
TypeError: tuple indices must be integers or slices, not str
```

The folder "input" has three 44.1 kHz mono audio files.

**Comment by pseeth** [comment]
Aha, will fix! Sorry, I guess I changed the output dictionary types in that PR. Will adjust!

**Comment by listener17** [comment]
Hi @pseeth: read in another issue thread that you were on parental leave. Congratulations! :-)

Did you have some time to look into this issue?

**Comment by listener17** [comment]
I've managed to fix it 😉

**Comment by pseeth** [comment]
Thank you @listener17! Sorry I never got to this. I incidentally also lost access to my GitHub for a while but just recovered it.
