### ISSUE TITLE
How is stereo compression done?

### ISSUE THREAD

**Issue by listener17** [descriptinc/descript-audio-codec#32]
Hello! 

This is connected to the question I asked after the issue (https://github.com/descriptinc/descript-audio-codec/issues/25) was closed. 

The "About" section of this repo says "Supports 44.1kHz, 24kHz, and 16kHz mono/stereo audio". 
However, the paper doesn't say anything special about stereo compression and/or stereo data. 

So, how is the stereo compression done currently? 
I understood that all the shared models (24 kHz and 44.1 kHz) are designed for mono compression only. 
If my understanding is correct, do you downmix the two channel and feed it to the encoder?
If yes, how do you recreate back the two channels in the decoder?  

Is there any documentation about your stereo compression scheme?

**Comment by listener17** [comment]
OK, I understood this question as well. Thanks.

**Comment by lwxyzove** [comment]
any update here？
