### ISSUE TITLE
different volume norm configuration from paper

### ISSUE THREAD

**Issue by seastar105** [descriptinc/descript-audio-codec#5]
may be it's not that important, volume norm seems different from paper

<img width="940" alt="image" src="https://github.com/descriptinc/descript-audio-codec/assets/30820469/3e021903-8317-4d9e-bcaa-09fb4c40ebc2">

below is base config in repo

https://github.com/descriptinc/descript-audio-codec/blob/98e762eaf030d078a47a9fc16485536f613c4412/conf/base.yml#L48

**Comment by ritheshkumar95** [comment]
Good observation. This was a typo in the paper. What we use in the code is the correct one. Thanks for pointing it out!
