### ISSUE TITLE
Encoding new file - use of `zero_pad`

### ISSUE THREAD

**Issue by v-i-s-h** [descriptinc/descript-audio-codec#50]
Hi, I am trying to understand the encoding procedure and is confused about this line in chunked inference:
https://github.com/descriptinc/descript-audio-codec/blob/c7cfc5d2647e26471dc394f95846a0830e7bec34/dac/model/base.py#L197

It is supposed to pad the signal with some 0s both at the start and the end. But, since the results is not stored anywhere, I wonder what is the use of this code?

**Comment by Cortexelus** [comment]
I *think* this is the receptive field of the convolutions. 
Each latent is based not just on its corresponding time range of audio, but also considers the before/after context. The first/last have nothing before/after, so zero padding is added. Here is an animation of 2D convolution, the dotted line is the zero padding.
![img](https://i.stack.imgur.com/iu9I7.gif)

**Comment by v-i-s-h** [comment]
Yes, this makes sense. Also, it seems like the `encode` task is disabling all the paddings in the conv layers. And, finally, `zero_pad` is in place operation and hence the results of it does not need to be stored.

Thanks for the clarification.
