### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by anusfoil** [descriptinc/descript-audio-codec#55]
Hi, I am trying to process my audio clip of each 1s segment, given the limitation of my GPU memory. However, the allocated memory seems to steadily increase throughout my loop of computing each segment: 

```
  signal.audio_data = signal.audio_data
  for i in range(num_segments):
      start = i * samples_per_segment
      end = min(start + samples_per_segment, total_samples)
      segment = signal.audio_data[:, :, start:end].to(dac_model.device)

      # Process each segment
      x = dac_model.preprocess(segment, signal.sample_rate)

      print("to begin", torch.cuda.memory_allocated(5))
      z, codes, latents, commitment_loss, codebook_loss = dac_model.encode(x)
      embeddings.append(rearrange(z, '1 e t -> t e').cpu()) 

      del x, z, codes, latents, commitment_loss, codebook_loss
      torch.cuda.empty_cache()
      print("to end", torch.cuda.memory_allocated(5))
```

Each time the z variable is computed, I move it to cpu and manually deletes all variables that's on the GPU, and cleaned torch cache. The only thing that's being kept on GPU is dac_model which I will use for the next iteration. Is the model itself aggregating memories? The memory print output show a steady increase like this until it reaches OOM. 

```
to begin 312585728
to end 10856556032
to begin 10858396160
to end 21401096704
```

I wonder is this the expected behavior or there is a memory leak somewhere? If it's expected, what is the correct practice of using DAC to compute encodings for segments of a long audio? I am on CentOS Linux 7 (Core), Python 3.7.5 and torch 1.13.1. This model is the 44khz one.

**Comment by lonce** [comment]
// Here is the fix to your memory problem!

with torch.no_grad():

       z, codes, latents, commitment_loss, codebook_loss = dac_model.encode(x)

**Comment by anusfoil** [comment]
Can't believe it's this simple!
