### ISSUE TITLE
Decode using codes instead of encoder output?

### ISSUE THREAD

**Issue by yiyousong** [descriptinc/descript-audio-codec#66]
```
x = model.preprocess(signal.audio_data, signal.sample_rate)
z, codes, latents, _, _ = model.encode(x)

# Decode audio signal
y = model.decode(z)
```
here z is the direct output of the encoder, without quantizing. this is incorrect as it does not "quantize" the input and the . However, I was unable to find how to decode the "codes" in your script. I checked with the 16khz model, and the decode function/model.decoder only accept unquantized direct output of the encoder which is ~100 times larger than the quantized codes.

I hope I missed something because if this is true, this means the model is an autoencoder instead of an RVQ-VAE.

**Comment by yiyousong** [comment]
@eeishaan I believe this is an highly important issue

**Comment by yuzuda283** [comment]
model.encode() func contains: audio -> encoder -> embedding - > codec -> codebook -> embedding'
and finally embedding'-> decoder-> audio,  "z" in code is the embedding' but not the output of encoder

**Comment by lastapple** [comment]
I think what he need is a function for codec -> codebook -> embedding'.
