### ISSUE TITLE
The size of tensor a (5) must match the size of tensor b (6) at non-singleton dimension 1

### ISSUE THREAD

**Issue by Sonal-Monteiro** [descriptinc/descript-audio-codec#70]
_ Iteration (train) 1001/250000                      0:26:39 / 84:38:24
           _ Iteration (val)   0/94                             0:00:00 / -:--:--
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original RuntimeError: The size of tensor a (5) must match the size of tensor b (6) at non-singleton dimension 1

Can someone help me with this?

**Comment by haidog-yaqub** [comment]
> ```
>        _ Iteration (train) 1001/250000                      0:26:39 / 84:38:24
>        _ Iteration (val)   0/94                             0:00:00 / -:--:--
> ```
> 
> RuntimeError: Caught RuntimeError in DataLoader worker process 0. Original RuntimeError: The size of tensor a (5) must match the size of tensor b (6) at non-singleton dimension 1
> 
> Can someone help me with this?

you need to convert all data to mono or stereo before training. this is an audiotools bug for 6-channel audio
