### ISSUE TITLE
about test sample demo

### ISSUE THREAD

**Issue by wl3b10s** [descriptinc/descript-audio-codec#8]
Hi, thanks for your work.

but when i click to play samples on page : https://descript.notion.site/Descript-Audio-Codec-11389fce0ce2419891d6591a68f814d5

it shows : this audio format wav can't 'be played' and it also can't be download to local drive.

this existed for me on both edge and chrome browser.

is it a problem from my PC or is there something need to be fix?

thank you.

**Comment by eeishaan** [comment]
Hi @wl3b10s thanks for reaching out. That issue is quite odd indeed. Since we use a widely used 3rd party software to host the samples, it's quite likely it's a problem with your PC. Perhaps there is a missing driver. Would you be willing to try the site on Firefox please?

**Comment by wl3b10s** [comment]
> 

thanks. I tried with another pc and got the test samples successfully.
