### ISSUE TITLE
How to encode audio with different settings?

### ISSUE THREAD

**Issue by ekgren** [descriptinc/descript-audio-codec#9]
Thank you for an amazing paper and OS release. I'm wondering how we can try different settings of the encoder decoder to test the quality of different number of code books for example. Do we need separately trained models for the different compression ratios or could you just provide some examples on how to do it?

**Comment by marypilataki** [comment]
Hello,

Thank you for providing your code!

Similar to ekgren, I was wondering how can I test different compression ratios and the impact on reconstruction quality. 
My understanding is that the model needs to be retrained with a different setting for encoder and decoder rates (stride settings). Is that correct? If so, could you please provide more checkpoints for those different settings if available?

Thanks!
Mary

**Comment by pseeth** [comment]
Different compression ratios can be passed in via the `n_quantizers` argument here: https://github.com/descriptinc/descript-audio-codec/blob/main/dac/model/dac.py#L268. This would be for the pretrained model. We currently don't have any other checkpoints trained, though, with different strides, but they may come if we have time and resources to train them!

**Comment by marypilataki** [comment]
Hey, thanks for the response!

I have tried between different numbers from 1 up to 9 (9 is the default setting if I am not mistaken) for n_quantizers. (--n_quantizers argument when encoding).

However, I cannot see any impact on the compressed .dac file, its size remains the same. I would expect the file size to change depending on the compression ratio. Am I missing something?

Cheers!

**Comment by ekgren** [comment]
> Different compression ratios can be passed in via the `n_quantizers` argument here: https://github.com/descriptinc/descript-audio-codec/blob/main/dac/model/dac.py#L268. This would be for the pretrained model. We currently don't have any other checkpoints trained, though, with different strides, but they may come if we have time and resources to train them!

In the script in the github readme  n_quantizers doesn't seem to change the compression ratio.

```
from dac.utils.encode import process as encode

# Encode audio signal
encoded_out = encode(signal, 'cuda', model, n_quantizers=n_quantizers)
print(encoded_out['codes'])

```

The codes returne are the same regardless of the number of n_quantizers put in.

**Comment by eeishaan** [comment]
@ekgren thank you for raising this issue

@marypilataki 
> However, I cannot see any impact on the compressed .dac file, its size remains the same. I would expect the file size to change depending on the compression ratio. Am I missing something?

Yes, this was a bug on our end. We have release a new version that works as expected.

Please update your dac installation.

```
pip install descript-audio-codec==0.0.3
```

**Comment by eeishaan** [comment]
@listener17  The default bitrate is 8kbps for the following command

```
python3 -m dac encode /path/to/input --output /path/to/output/codes
```

**Comment by marypilataki** [comment]
Great, thanks so much for the prompt response!
